### ISSUE TITLE
Valheim Plus

### ISSUE THREAD

**Issue by NiceATC** [akridge/Oracle-Cloud-Free-Valheim-Game-Server-Setup#1]
the mod does not start with the server, I am using LGSM

**Comment by akridge** [comment]
Hmm, yeah might be a limitation of current V+ & LGSM. I switched to AMP early on because of its ease of use. 

Try this for LGSM:
1. Edit start_server_bepinex.sh and replace the arguments of Valheim executable with $@ so the last line looks like this :
exec ./valheim_server.x86_64 $@

2. Add executable="./start_server_bepinex.sh" to your your vhserver.cfg

Note: Adding this to guide. Please let me know if you have any trouble with it. Cheers, -M
